# Site settings
name: "Swiss Wood Solutions"
description: "site for Swiss Wood Solutions"
url: "http://swisswoodsolutions.github.io"
githubUsername: SwissWoodSolutions

# see https://github.com/github/jekyll-commonmark-ghpages
markdown: CommonMarkGhPages
commonmark:
  extensions: ["table"]

# Build settings
permalink: pretty
